/**
 * @page platform/gulp/tasks/clean clean
 * @parent platform/gulp/tasks
 *
 * Removes files and directories
 *
 * @signature `gulp clean:docs`
 * Removes all files generated by the [platform/gulp/tasks/docs docs] task.
 *
 * @signature `gulp clean:build`
 * Removes all files generated by the [platform/gulp/tasks/build build] task.
*/

var gulp = require('gulp');
var del = require('del');
var config = require('../config');

gulp.task('clean:docs', function () {
    return del([config.documentjs.siteConfig.dest]);
});

gulp.task('clean:build', function () {
    return del(['target']);
});
