/**
 * @page platform/gulp/tasks/default default
 * @parent platform/gulp/tasks
 *
 * This is the task that runs when no task name is given to gulp.
 *
 * @signature `gulp`
 * Removes all files generated by the [platform/gulp/tasks/watch watch] task.
*/

var gulp = require('gulp');

gulp.task('default', ['xo', 'watch:app']);
